Improviment init-ocp script

diff --git a/confs/init-ocp-configd b/confs/init-ocp-configd
--- a/confs/init-ocp-configd
+++ b/confs/init-ocp-configd
@@ -3,134 +3,164 @@
 OCP_LATEST_VERSION=$(curl -s ${OCP_BASEURL}/release.txt | grep 'Version: ' | awk '{print $2}')
 OCP_API="api api-int"
 OCP_APPS='*.apps'
+nodes="_etcd-server-ssl._tcp ${OCP_BOOTSTRAP_IGN_DNSNAME} ${OCP_API} ${OCP_APPS} ${MASTERS_DNS_NAMES} ${ETCD_DNS_NAMES} ${WORKERS_DNS_NAMES}"
 
-test_dns_to_ip(){
-  if [ "$IP" != "" ]
-  then
-    echo "OK"
-  else
-    echo "----------------------------------------------------------------------------"
-    echo "!!DNS _etcd-server-ssl._tcp.${CLUSTER_NAME}.${BASE_DOMAIN} is not configured!!"
-    echo "!!For proceed the installation you need to configure all DNS listed before!!"
-    echo "----------------------------------------------------------------------------"
-    exit 1
-  fi
-}
-
-echo "------------------!!Listing configured DNS names!!------------------"
-echo "###########################"
-for nodeName in ${MASTERS_DNS_NAMES} ${ETCD_DNS_NAMES} ${WORKERS_DNS_NAMES}
-do
-  echo "$nodeName.${CLUSTER_NAME}.${BASE_DOMAIN}"
-done
-echo "###########################"
-
-for nodeType in `echo "masters etcds workers"`
-do  
-  nodes=""
-  if [ $nodeType == "masters" ]
-  then
-    nodes=${MASTERS_DNS_NAMES}
-  elif [ $nodeType == "etcds" ]
-  then
-    nodes=${ETCD_DNS_NAMES}
-    echo "Testing SRV _etcd-server-ssl._tcp.${CLUSTER_NAME}.${BASE_DOMAIN}"
-    IP=`dig _etcd-server-ssl._tcp.${CLUSTER_NAME}.${BASE_DOMAIN} SRV +short`
-    test_dns_to_ip
-  else
-    nodes=${WORKERS_DNS_NAMES}
-  fi
-  
-  sleep 2
-  echo "------------------Testing $nodeType nodes dns names------------------"
-  for nodeName in $OCP_BOOTSTRAP_IGN_DNSNAME $OCP_API $OCP_APPS $nodes; do
-    echo "Testing $nodeName.${CLUSTER_NAME}.${BASE_DOMAIN}"
-    IP=`dig $nodeName.${CLUSTER_NAME}.${BASE_DOMAIN} +short`
-    test_dns_to_ip
-  done
-done
-
-exit 55
 
 echo "Setting permission to $(whoami) user "
 sudo chown $(whoami):$(whoami) ${OCP_USER_PATH} -R
 
-echo "Downloading openshift-install cli"
-if [ ! -f ${OCP_USER_PATH}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz ]
-then
-    curl -s ${OCP_BASEURL}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} oc kubectl
-    curl -s ${OCP_BASEURL}/openshift-install-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} openshift-install
-fi
+ifFQDNisActive(){
+  if [ ${node} == "_etcd-server-ssl._tcp" ]
+  then
+    fqdn="${node}.${CLUSTER_NAME}.${BASE_DOMAIN} SRV"
+  else
+    fqdn="${node}.${CLUSTER_NAME}.${BASE_DOMAIN}"
+  fi
 
-echo "------------------TPreparing the install environments------------------T"
-
-echo "Generating Manisfests files"
-${OCP_USER_PATH}/openshift-install create manifests --dir=${OCP_USER_PATH}
-sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' ${OCP_USER_PATH}/manifests/cluster-scheduler-02-config.yml
-
-echo "Generating Ignitions files"
-${OCP_USER_PATH}/openshift-install create ignition-configs --dir=${OCP_USER_PATH}
-
-echo "Secondary Ignition config file for your bootstrap node to your computer"
-
-cat <<EOF > ${OCP_USER_PATH}/append-bootstrap.ign
-{
-  "ignition": {
-    "config": {
-      "append": [
-        {
-          "source": "http://${OCP_BOOTSTRAP_IGN_DNSNAME}.${CLUSTER_NAME}.${BASE_DOMAIN}/ocp${OCP_USERID}/ignition/bootstrap.ign",
-          "verification": {}
-        }
-      ]
-    },
-    "timeouts": {},
-    "version": "2.1.0"
-  },
-  "networkd": {},
-  "passwd": {},
-  "storage": {},
-  "systemd": {}
+  ip=`dig ${fqdn} +short`
+  
+  [[ -z "$ip" ]] && echo "false" || echo "true"
 }
+
+list_cluster_nodes_names(){
+  echo "------------------list_cluster_nodes_names-------------------------"
+  for node in ${nodes}
+  do
+    echo "$node.${CLUSTER_NAME}.${BASE_DOMAIN}"
+  done
+  echo "------------------END Listing Cluster DNS Names---------------------"
+}
+
+checking_cluster_dns_nodes_names() {
+  
+  list_cluster_nodes_names
+
+  echo "------------------checking_cluster_dns_nodes_names------------------------"
+  for node in ${nodes}
+  do
+    fqdnActive=$(ifFQDNisActive)
+    if [  "$fqdnActive" == "true" ]
+    then
+      echo "[DNS OK] - ${node}.${CLUSTER_NAME}.${BASE_DOMAIN}"
+    else
+      echo "[DNS FAIL] - ${node}.${CLUSTER_NAME}.${BASE_DOMAIN}"
+    fi  
+  done
+  echo "------------------END checking_cluster_dns_nodes_names---------------------"
+}
+
+downloading_installers(){
+  echo "------------------downloading_installers------------------------"
+
+  echo "Downloading openshift-install cli"
+  if [ ! -f ${OCP_USER_PATH}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz ]
+  then
+      curl -s ${OCP_BASEURL}/openshift-client-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} oc kubectl
+      curl -s ${OCP_BASEURL}/openshift-install-linux-${OCP_LATEST_VERSION}.tar.gz | tar -xzf - -C ${OCP_USER_PATH} openshift-install
+  fi
+
+  if [ ${TIER} == "vsphere" ]
+  then
+    echo "Downloading ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-vmware.ova"
+    curl ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-vmware.ova -o ${OCP_USER_PATH}/sharedfolder/rhcos-4.3.0-x86_64-vmware.ova -#
+    cp -rv ${OCP_USER_PATH}/sharedfolder/rhcos-4.3.0-x86_64-vmware.ova /var/www/html/ocp${OCP_USERID}/ignition
+    
+    if [ "${isNodesWithDHCP}" == "false" ]
+    then
+      echo "Enviroment without DHCP server to Nodes"
+      echo "Downloading ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-metal.raw.gz"
+      curl ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-metal.raw.gz -o ${OCP_USER_PATH}/sharedfolder/rhcos-4.3.0-x86_64-metal.raw.gz -#
+      cp -rv ${OCP_USER_PATH}/sharedfolder/rhcos-4.3.0-x86_64-metal.raw.gz /var/www/html/ocp${OCP_USERID}/ignition
+    fi
+  fi
+
+  echo "------------------End downloading_installers------------------------"
+}
+
+generate_manisfests_files(){
+  echo "------------------generate_manisfests_files------------------------"
+
+  ${OCP_USER_PATH}/openshift-install create manifests --dir=${OCP_USER_PATH}
+  sed -i 's/mastersSchedulable: true/mastersSchedulable: false/g' ${OCP_USER_PATH}/manifests/cluster-scheduler-02-config.yml
+  
+  echo "------------------END generate_manisfests_files------------------------"
+}
+
+generate_ignitions_files(){
+  echo "------------------generate_ignitions_files------------------------"
+
+  ${OCP_USER_PATH}/openshift-install create ignition-configs --dir=${OCP_USER_PATH}
+
+  echo "Generating secondary Ignition config file for your bootstrap node to your computer"
+  cat <<EOF > ${OCP_USER_PATH}/append-bootstrap.ign
+  {
+    "ignition": {
+      "config": {
+        "append": [
+          {
+            "source": "http://${OCP_BOOTSTRAP_IGN_DNSNAME}.${CLUSTER_NAME}.${BASE_DOMAIN}/ocp${OCP_USERID}/ignition/bootstrap.ign",
+            "verification": {}
+          }
+        ]
+      },
+      "timeouts": {},
+      "version": "2.1.0"
+    },
+    "networkd": {},
+    "passwd": {},
+    "storage": {},
+    "systemd": {}
+  }
 EOF
 
-echo "Generating files in base64"
+  echo "Generating files in base64"
+  for i in append-bootstrap master worker
+  do
+      base64 -w0 < $i.ign > $i.64
+  done
 
-for i in append-bootstrap master worker
-do
-    base64 -w0 < $i.ign > $i.64
-done
+  echo "Copy ${OCP_USER_PATH}/*.ign to WebServer"
+  cp -rv ${OCP_USER_PATH}/*.ign /var/www/html/ocp${OCP_USERID}/ignition
 
-mkdir -p /var/www/html/ocp${OCP_USERID}/ignition
+  echo "------------------END generate_ignitions_files------------------------"
+}
 
-echo "Configuring RHCOS to TIER ${TIER}"
-if [ ${TIER} == "vsphere" ]
-then
-    cd ${OCP_USER_PATH}/sharedfolder
-    rm -rf ${OCP_USER_PATH}/sharedfolder/*
+configuring_webserver_nginx(){
+  echo "------------------configuring_webserver_nginx------------------------"
 
-    echo "Downloading ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-vmware.ova"
-    curl ${RHCOS_PACKAGES}/rhcos-4.3.0-x86_64-vmware.ova -o nul -#
-    
-    cp -rv ${OCP_USER_PATH}/sharedfolder/rhcos-4.3.0-x86_64-vmware.ova /var/www/html/ocp${OCP_USERID}/ignition
+  echo "Creating path /var/www/html/ocp${OCP_USERID}/ignition"
+  mkdir -p /var/www/html/ocp${OCP_USERID}/ignition
 
-    echo "Copy generated files .64 to ${OCP_USER_PATH}/sharedfolder/"
-    cp -rv ${OCP_USER_PATH}/*.64  ${OCP_USER_PATH}/sharedfolder/
-fi
+  echo "------------------End configuring_webserver_nginx------------------------"
+}
 
-echo "Initializing Apache to bastion"
-if [ -f ${OCP_USER_PATH}/bootstrap.ign ]
-then
-  cp -rv ${OCP_USER_PATH}/bootstrap.ign /var/www/html/ocp${OCP_USERID}/ignition
-fi
+copying_configurations_to_shared_folder(){
 
-if [ -d ${OCP_USER_PATH}/auth ]
-then
-  cp -rv ${OCP_USER_PATH}/auth ${OCP_USER_PATH}/sharedfolder/
-fi
+  cd ${OCP_USER_PATH}/sharedfolder
+  rm -rf ${OCP_USER_PATH}/sharedfolder/*
 
-echo "----------------------------------------------------------------------------------------------------"
-echo "Files configurated on: ~/ocp/sharedfolder/"
-echo "URL to access ignation and RHCOS OVA: http://${OCP_BOOTSTRAP_IGN_DNSNAME}.${CLUSTER_NAME}.${BASE_DOMAIN}/ocp${OCP_USERID}/ignition/"
-echo "Openshift credentials files: ~/ocp/sharedfolder/auth"
-echo "----------------------------------------------------------------------------------------------------"
+  echo "Copy generated files .64 to ${OCP_USER_PATH}/sharedfolder/"
+  cp -rv ${OCP_USER_PATH}/*.64 ${OCP_USER_PATH}/auth ${OCP_USER_PATH}/sharedfolder/
+
+  echo "Instalation Information----------" >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+  echo "Files configurated on: ~/ocp/sharedfolder/" >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+  echo "URL to access ignation and RHCOS OVA: http://${OCP_BOOTSTRAP_IGN_DNSNAME}.${CLUSTER_NAME}.${BASE_DOMAIN}/ocp${OCP_USERID}/ignition/" >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+  echo "Openshift credentials files: ~/ocp/sharedfolder/auth" >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+  list_cluster_nodes_names >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+  echo "--------------------------------" >> ${OCP_USER_PATH}/sharedfolder/configurations.txt
+
+  cat ${OCP_USER_PATH}/sharedfolder/configurations.txt
+
+}
+
+checking_cluster_dns_nodes_names
+
+configuring_webserver_nginx
+
+downloading_installers
+
+generate_manisfests_files
+
+generate_ignitions_files
+
+copying_configurations_to_shared_folder
